// library-data.js — curated training catalogs for the Exercise Library.
// Built from researched sources (HYROX rulebook/RoxLyfe, r/bodyweightfitness RR +
// Overcoming Gravity standards, Stronger by Science, USMS/MySwimPro, boxing
// coaching refs, NSCA/ACSM-aligned anatomy). Loaded before library.js.
//
// Entry: { name, target, muscles, equip, cues, mistake, prog, img (free-exercise-db
// id or null), icon, video (YouTube search terms) }
// Ladder: { name, trains, icon, video, steps: [{ name, std }] } — std = advance rule.

const LIB_TRAINING = {

  // ============================================================
  hyrox: {
    label: 'Hyrox',
    icon: '🏃',
    blurb: 'The 8 race stations (Men’s Open weights) + the standard prep movements. Race = 8×1 km runs, one station after each.',
    groups: [
      { title: 'Race stations', items: [
        { name: 'SkiErg', target: '1000 m', muscles: 'lats · triceps · core', equip: 'SkiErg', icon: '🎿', img: 'Straight-Arm_Pulldown', video: 'skierg+technique+hyrox',
          cues: 'Full-body “crunch” from hips + lats, long strokes ~35–45 spm', mistake: 'Sprinting the first 250 m — spikes HR before the sleds', prog: 'Build 400 m → 1000 m, then chase pace' },
        { name: 'Sled Push', target: '50 m · 152 kg', muscles: 'quads · glutes · calves', equip: 'sled', icon: '🛷', img: 'Sled_Push', video: 'hyrox+sled+push+technique',
          cues: 'Low ~45° body angle, short powerful steps, keep it moving', mistake: 'Standing too upright — kills force transfer', prog: 'Sub: heavy leg-press clusters · DB march · plate push on turf' },
        { name: 'Sled Pull', target: '50 m · 103 kg', muscles: 'lats · biceps · grip · posterior chain', equip: 'sled + rope', icon: '🪝', img: 'Sled_Row', video: 'hyrox+sled+pull+technique',
          cues: 'Stay low, lean back, hand-over-hand with constant rope tension', mistake: 'Arms-only pulling — fries grip before farmers carry', prog: 'Sub: heavy seated cable rows · towel-plate backward drags' },
        { name: 'Burpee Broad Jumps', target: '80 m', muscles: 'full body', equip: 'none', icon: '🤸', img: 'Standing_Long_Jump', video: 'burpee+broad+jump+form',
          cues: 'Chest to floor, feet together on the jump, modest ~1 m hops, steady rhythm', mistake: 'Max jumps early — torches the quads', prog: 'Knees-up standing is legal; 40 m → 80 m' },
        { name: 'RowErg', target: '1000 m', muscles: 'posterior chain · lats', equip: 'rower', icon: '🚣', img: 'Rowing_Stationary', video: 'rowerg+technique+hyrox',
          cues: 'Legs–body–arms, ~22–28 spm; this is your recovery station', mistake: 'Pulling a 2k-PR split — costs minutes later', prog: 'Build 400 m → 1000 m at controlled split' },
        { name: 'Farmers Carry', target: '200 m · 2×24 kg', muscles: 'grip · traps · core', equip: 'kettlebells/DBs', icon: '🧳', img: 'Farmers_Walk', video: 'farmers+carry+technique',
          cues: 'Tall posture, shoulders packed, quick short steps', mistake: 'Setting the bells down — each drop costs 10–15 s', prog: 'Heavier DBs, fewer breaks; 2×16 → 2×24 kg' },
        { name: 'Sandbag Lunges', target: '100 m · 20 kg', muscles: 'quads · glutes · hamstrings', equip: 'sandbag', icon: '🦵', img: 'Dumbbell_Rear_Lunge', video: 'sandbag+walking+lunge',
          cues: 'Bag high on traps, chest up, rear knee touches every rep', mistake: 'Leaning forward under the bag — loads the lower back', prog: 'Sub: goblet/back-rack walking lunges; 8 → 20 kg' },
        { name: 'Wall Balls', target: '100 reps · 6 kg → 3 m', muscles: 'quads · glutes · shoulders', equip: 'med ball', icon: '🏐', img: 'Medicine_Ball_Scoop_Throw', video: 'wall+ball+shot+form',
          cues: 'Full squat, one throw–catch–ride-down rhythm; break early on purpose (25/25/25/25)', mistake: 'Missing the 3 m target when tired — no-reps', prog: 'Sub: DB thrusters · med-ball throw-ups; 40 → 100 reps' },
      ]},
      { title: 'Prep movements', items: [
        { name: 'Kettlebell Swing', target: '3×15', muscles: 'glutes · hamstrings · grip', equip: 'kettlebell', icon: '🏋️', img: 'One-Arm_Kettlebell_Swings', video: 'kettlebell+swing+form',
          cues: 'Hinge not squat; snap the hips, arms are ropes', mistake: 'Squatting the swing', prog: 'Deadlift-to-stand → swing → heavier bell' },
        { name: 'Weighted Step-Up', target: '3×8/leg', muscles: 'quads · glutes', equip: 'box + DBs', icon: '🦵', img: 'Dumbbell_Step_Ups', video: 'dumbbell+step+up+form',
          cues: 'Full foot on box, drive without pushing off the back leg', mistake: 'Bouncing off the rear leg', prog: 'Low box → knee height → +DBs' },
        { name: 'Dead-Ball Over Shoulder', target: '3×8', muscles: 'posterior chain', equip: 'dead ball/sandbag', icon: '🏐', img: null, video: 'dead+ball+over+shoulder',
          cues: 'Hips under, lap the ball, extend and throw over the shoulder', mistake: 'Rounding the back on the pick', prog: 'Light ball → race-weight sandbag' },
        { name: 'Assault Bike Intervals', target: '10×45 s hard / 75 s easy', muscles: 'full body', equip: 'air bike', icon: '🚴', img: 'Bicycling_Stationary', video: 'assault+bike+intervals',
          cues: 'Big gears with legs, steady pull with arms', mistake: 'All-out first interval', prog: 'Add intervals or shrink the rest' },
        { name: 'Goblet Squat', target: '3×12', muscles: 'quads · core', equip: 'KB/DB', icon: '🏋️', img: 'Goblet_Squat', video: 'goblet+squat+form',
          cues: 'Elbows inside knees, full depth, heels down', mistake: 'Heels lifting', prog: 'Bodyweight → goblet → double-KB front squat' },
        { name: 'Romanian Deadlift', target: '3×10', muscles: 'hamstrings · glutes', equip: 'barbell/DBs', icon: '🏋️', img: 'Romanian_Deadlift', video: 'romanian+deadlift+form',
          cues: 'Soft knees, hips back, flat back to mid-shin', mistake: 'Squatting the hinge', prog: 'Hinge drill → RDL → single-leg RDL' },
        { name: 'Weighted-Vest Run', target: '4×400 m race pace', muscles: 'legs · aerobic system', equip: '5–10 kg vest', icon: '🏃', img: 'Running_Treadmill', video: 'weighted+vest+running',
          cues: 'Short race-pace reps only, tall posture', mistake: 'Long slow vest runs — joint stress, little gain', prog: 'Add reps before adding vest weight' },
        { name: 'Compromised-Run Brick', target: '4–6×(1 km + station)', muscles: 'full body', equip: 'varies', icon: '🧱', img: null, video: 'hyrox+compromised+running',
          cues: 'Station → run at goal pace; find your legs within 200 m', mistake: 'Standing rest between station and run', prog: 'Classic brick → station sandwich → half-Hyrox sim' },
      ]},
    ],
  },

  // ============================================================
  calisthenics: {
    label: 'Calisthenics',
    icon: '🤸',
    blurb: 'Skill ladders, easiest → hardest. Rule: hit 3×8 clean reps (or 3×20–30 s hold) → move up a step and restart at 3×5. Can’t get 3×5 → move down.',
    ladders: [
      { name: 'Push-Up Ladder', trains: 'chest · front delts · triceps · core', icon: '🫸', video: 'push+up+progression', img: 'Pushups',
        steps: [
          { name: 'Wall push-up', std: '3×15' }, { name: 'Incline push-up', std: '3×8–12' }, { name: 'Knee push-up', std: '3×10–15' },
          { name: 'Full push-up', std: '3×8 clean' }, { name: 'Diamond push-up', std: '3×8' }, { name: 'Decline push-up', std: '3×8' },
          { name: 'Pseudo-planche push-up', std: '3×8 moderate lean' }, { name: 'Archer push-up', std: '3×6/side' }, { name: 'One-arm progressions', std: '3×5/side per stage' },
        ]},
      { name: 'Pull-Up Ladder', trains: 'lats · biceps · scapular control · grip', icon: '🫷', video: 'pull+up+progression', img: 'Pullups',
        steps: [
          { name: 'Dead hang', std: '3×30–60 s' }, { name: 'Scapular pulls', std: '3×8' }, { name: 'Negatives (3–5 s down)', std: '3×5–8' },
          { name: 'Band-assisted pull-up', std: '3×8 lightest band' }, { name: 'Full pull-up', std: '3×8' }, { name: 'Chest-to-bar', std: '3×6–8' },
          { name: 'Archer pull-up', std: '3×5/side' }, { name: 'Typewriter pull-up', std: '3×4–6/side' }, { name: 'Weighted pull-up', std: '3×5 @ +10–15% BW' },
          { name: 'Muscle-up transition negatives', std: '3×3–5 slow' },
        ]},
      { name: 'Dip Ladder', trains: 'lower chest · triceps · front delts', icon: '💪', video: 'dip+progression', img: 'Dips_-_Triceps_Version',
        steps: [
          { name: 'Support hold', std: '3×30 s' }, { name: 'Bench dips', std: '3×10–12' }, { name: 'Dip negatives (3–5 s)', std: '3×5–8' },
          { name: 'Parallel-bar dips', std: '3×8' }, { name: 'Ring dips', std: '3×8' }, { name: 'Weighted dips', std: 'load at 3×5–8' },
        ]},
      { name: 'Squat Ladder', trains: 'quads · glutes · balance · ankle mobility', icon: '🦵', video: 'pistol+squat+progression', img: 'Bodyweight_Squat',
        steps: [
          { name: 'Assisted squat', std: '3×10–15' }, { name: 'Bodyweight squat', std: '3×15–20' }, { name: 'Split squat', std: '3×8/side' },
          { name: 'Bulgarian split squat', std: '3×8/side' }, { name: 'Shrimp squat', std: '3×6–8/side' }, { name: 'Assisted pistol', std: '3×6/side' },
          { name: 'Full pistol squat', std: '3×5/side clean' },
        ]},
      { name: 'Handstand Ladder', trains: 'shoulders · traps · wrists · balance', icon: '🤸', video: 'handstand+progression', img: 'Handstand_Push-Ups',
        steps: [
          { name: 'Wall plank / pike hold', std: '3×30–60 s' }, { name: 'Wall walk', std: '3×3–5 walks' }, { name: 'Chest-to-wall hold', std: '1×60 s' },
          { name: 'Kick-up practice', std: '5–10 s balance touches' }, { name: 'Freestanding handstand', std: '10–20 s consistent' },
          { name: 'Pike push-up', std: '3×8' }, { name: 'Wall HSPU negatives', std: '3×5' }, { name: 'Wall HSPU', std: '3×5 full ROM' },
        ]},
      { name: 'L-Sit Ladder', trains: 'hip flexors · abs · triceps · compression', icon: '🪑', video: 'l+sit+progression', img: null,
        steps: [
          { name: 'Foot-supported L-sit', std: '3×20–30 s' }, { name: 'Tuck L-sit', std: '3×20–30 s' }, { name: 'One-leg L-sit', std: '3×10–15 s/leg' },
          { name: 'Full L-sit', std: '3×10–20 s' }, { name: 'V-sit', std: '3×5–10 s per angle' },
        ]},
      { name: 'Front Lever Ladder', trains: 'lats · core anti-extension · straight-arm pull', icon: '🦇', video: 'front+lever+progression', img: null,
        steps: [
          { name: 'Tuck front lever', std: '3×20–30 s' }, { name: 'Advanced tuck', std: '3×15–20 s' }, { name: 'One-leg front lever', std: '3×10–15 s/side' },
          { name: 'Straddle front lever', std: '3×8–12 s' }, { name: 'Full front lever', std: '3×5–10 s' },
        ]},
      { name: 'Back Lever Ladder', trains: 'chest · front delts · biceps tendons (go slow!)', icon: '🦇', video: 'back+lever+progression', img: null,
        steps: [
          { name: 'Tuck back lever', std: '3×20–30 s' }, { name: 'Advanced tuck', std: '3×15–20 s' }, { name: 'One-leg back lever', std: '3×10–15 s/side' },
          { name: 'Straddle back lever', std: '3×8–12 s' }, { name: 'Full back lever', std: '3×5–10 s' },
        ]},
      { name: 'Core: Plank → Ab Wheel', trains: 'anti-extension core', icon: '🧱', video: 'ab+wheel+progression', img: 'Ab_Roller',
        steps: [
          { name: 'Plank', std: '60 s clean' }, { name: 'RKC plank (max tension)', std: '3×10–20 s' }, { name: 'Kneeling rollout', std: '3×8' },
          { name: 'Partial standing rollout', std: '3×8' }, { name: 'Full standing ab-wheel rollout', std: '3×8' },
        ]},
      { name: 'Core: Hollow → Dragon Flag', trains: 'abs · full-body tension', icon: '🐉', video: 'dragon+flag+progression', img: null,
        steps: [
          { name: 'Hollow-body hold', std: '30 s perfect' }, { name: 'Tuck dragon flag', std: '3×6–8' }, { name: 'Single-leg dragon flag', std: '3×5–6' },
          { name: 'Full dragon flag', std: '3×5 controlled' },
        ]},
    ],
  },

  // ============================================================
  home: {
    label: 'Home',
    icon: '🏠',
    blurb: 'Minimal-kit training. Hypertrophy and beginner→intermediate strength are fully trainable at home; max-strength barbell work isn’t. Sub table per gym lift is inside each card.',
    groups: [
      { title: 'Top home exercises', items: [
        { name: 'Push-Up', target: '3×AMRAP−2', muscles: 'chest · triceps · delts', equip: 'none', icon: '🫸', img: 'Pushups', video: 'push+up+form',
          cues: 'Rigid plank; elbows ~45°', mistake: 'Sagging hips', prog: 'Incline → floor → deficit/weighted' },
        { name: 'Pike Push-Up', target: '3×8', muscles: 'shoulders · triceps', equip: 'none', icon: '🤸', img: null, video: 'pike+push+up+form',
          cues: 'Hips high; head travels ahead of hands', mistake: 'Turning it into a push-up', prog: 'Pike → feet-elevated → wall HSPU' },
        { name: 'Pull-Up', target: '3×5–8', muscles: 'lats · biceps', equip: 'bar', icon: '🫷', img: 'Pullups', video: 'pull+up+form',
          cues: 'Dead-hang start; chest to bar', mistake: 'Kipping / partial range', prog: 'Band-assisted → strict → weighted (backpack)' },
        { name: 'Inverted Row', target: '3×8–12', muscles: 'mid-back · biceps', equip: 'table/rings', icon: '🫷', img: 'Inverted_Row', video: 'inverted+row+form',
          cues: 'Straight body; squeeze the blades', mistake: 'Hips dropping', prog: 'Bent knees → straight → feet elevated' },
        { name: 'Goblet Squat', target: '3×8–12', muscles: 'quads · glutes', equip: 'DB/KB', icon: '🦵', img: 'Goblet_Squat', video: 'goblet+squat+form',
          cues: 'Elbows inside knees; heels down', mistake: 'Heels lifting', prog: 'Bodyweight → goblet → double-KB front squat' },
        { name: 'Bulgarian Split Squat', target: '3×8/leg', muscles: 'quads · glutes', equip: 'chair (+DBs)', icon: '🦵', img: 'Split_Squat_with_Dumbbells', video: 'bulgarian+split+squat+form',
          cues: 'Slight forward lean; knee tracks toes', mistake: 'Pushing off the back foot', prog: 'Split squat → rear-foot-elevated → +DBs (subs for back squat)' },
        { name: 'DB Romanian Deadlift', target: '3×10', muscles: 'hamstrings · glutes', equip: 'DBs/KB', icon: '🏋️', img: 'Romanian_Deadlift', video: 'dumbbell+romanian+deadlift',
          cues: 'Hips back; flat back', mistake: 'Squatting the hinge', prog: 'Hinge drill → RDL → single-leg RDL (subs for deadlift)' },
        { name: 'KB Swing', target: '3×15', muscles: 'glutes · hamstrings', equip: 'KB', icon: '🏋️', img: 'One-Arm_Kettlebell_Swings', video: 'kettlebell+swing+form',
          cues: 'Hike, snap hips; arms relaxed', mistake: 'Squat-and-lift, no hinge', prog: 'Deadlift-to-stand → swing → single-arm' },
        { name: 'Slider Leg Curl', target: '3×8', muscles: 'hamstrings', equip: 'towel/sliders', icon: '🦵', img: 'Ball_Leg_Curl', video: 'slider+leg+curl',
          cues: 'Hips high; ribs down', mistake: 'Hips drop as legs extend', prog: 'Glute bridge → sliders → eccentric Nordic → full Nordic (subs for leg curl)' },
        { name: 'DB Hip Thrust', target: '3×10', muscles: 'glutes', equip: 'couch + DB', icon: '🍑', img: 'Barbell_Hip_Thrust', video: 'dumbbell+hip+thrust',
          cues: 'Chin tucked; vertical shin at lockout', mistake: 'Hyperextending the spine', prog: 'Bridge → thrust → single-leg +DB' },
        { name: 'Step-Up', target: '3×8/leg', muscles: 'quads · glutes', equip: 'step + DBs', icon: '🦵', img: 'Dumbbell_Step_Ups', video: 'step+up+form',
          cues: 'Full foot on step; minimal push-off', mistake: 'Bouncing off the back leg', prog: 'Low box → knee height → +DBs' },
        { name: 'Single-Leg Calf Raise', target: '3×15/leg', muscles: 'calves', equip: 'step', icon: '🦶', img: 'Standing_Calf_Raises', video: 'single+leg+calf+raise',
          cues: 'Full stretch; 2 s pause at top', mistake: 'Bouncing', prog: 'Two-leg → single → +DB' },
        { name: 'DB Floor Press', target: '3×8', muscles: 'chest · triceps', equip: 'DBs', icon: '🫸', img: 'Dumbbell_Floor_Press', video: 'dumbbell+floor+press',
          cues: 'Wrists over elbows; light arm touch on floor', mistake: 'Flaring elbows to 90°', prog: 'Two-DB → single-arm → slow eccentric (subs for bench)' },
        { name: 'Single-Arm DB Row', target: '3×10/arm', muscles: 'lats · mid-back', equip: 'DB + chair', icon: '🫷', img: 'One-Arm_Dumbbell_Row', video: 'one+arm+dumbbell+row',
          cues: 'Elbow to hip; square torso', mistake: 'Twisting / jerking', prog: 'Supported → heavy → paused reps (subs for barbell row)' },
        { name: 'Standing DB Press', target: '3×8', muscles: 'delts · triceps', equip: 'DBs/KB', icon: '🫸', img: 'Dumbbell_Shoulder_Press', video: 'standing+dumbbell+press',
          cues: 'Squeeze glutes; biceps to ears', mistake: 'Leaning back', prog: 'Seated → standing → single-arm KB (subs for OHP)' },
        { name: 'Pallof Press', target: '2×12/side', muscles: 'obliques · deep core', equip: 'band', icon: '🧱', img: 'Pallof_Press', video: 'pallof+press+form',
          cues: 'Press straight out; resist the twist', mistake: 'Rotating toward the anchor', prog: 'Tall-kneeling → standing → walkout' },
        { name: 'Dead Bug / Hollow Hold', target: '3×10', muscles: 'deep core', equip: 'none', icon: '🪲', img: 'Dead_Bug', video: 'dead+bug+exercise',
          cues: 'Low back glued down; slow exhale', mistake: 'Ribs flaring', prog: 'Dead bug → hollow hold → hollow rocks' },
        { name: 'Single-Leg Glute Bridge', target: '3×10/leg', muscles: 'glutes', equip: 'none', icon: '🍑', img: 'Butt_Lift_Bridge', video: 'single+leg+glute+bridge',
          cues: 'Drive the heel; squeeze at top', mistake: 'Arching the low back', prog: 'Two-leg → single → shoulders-elevated +DB' },
      ]},
    ],
  },

  // ============================================================
  swim: {
    label: 'Swim',
    icon: '🏊',
    blurb: 'Strokes + drills for fitness swimming. Workout skeleton: warm-up → drills → main set → kick/pull → cool-down. “4×100 @ 2:00” = leave every 2 min.',
    groups: [
      { title: 'Strokes', items: [
        { name: 'Freestyle', target: 'default fitness stroke', muscles: 'lats · pecs · delts · core · legs', equip: 'pool', icon: '🏊', img: null, video: 'freestyle+swimming+technique',
          cues: 'Long horizontal line, eyes down · high-elbow catch · rotate from the hips', mistake: 'Lifting the head to breathe — hips sink', prog: 'Catch-up drill → fingertip drag → bilateral breathing' },
        { name: 'Backstroke', target: 'recovery stroke', muscles: 'lats · rear delts · core · glutes', equip: 'pool', icon: '🏊', img: null, video: 'backstroke+technique',
          cues: 'Flat head, eyes up, hips at surface · pinky-first entry at 11 & 1', mistake: '“Sitting” in the water when the head lifts', prog: 'Kick on back → single-arm → full stroke' },
        { name: 'Breaststroke', target: 'easy-day stroke', muscles: 'quads · glutes · adductors · pecs', equip: 'pool', icon: '🏊', img: null, video: 'breaststroke+technique',
          cues: 'Pull → breathe → kick → GLIDE · heels to hips, feet flexed, snap together', mistake: 'No glide — constant churning', prog: 'Kick on back → 2-kicks-1-pull → full timing. Note: whip kick can bug knees' },
        { name: 'Butterfly', target: 'short doses (25s)', muscles: 'lats · pecs · delts · core — fullest engagement', equip: 'pool', icon: '🏊', img: null, video: 'butterfly+stroke+technique',
          cues: 'Undulate from chest & hips · 2 dolphin kicks per cycle · low forward breath', mistake: 'Muscling with arms alone — gone in one length', prog: 'Body dolphin → 2-kicks-1-pull → full stroke 25s' },
      ]},
      { title: 'Drills', items: [
        { name: 'Catch-Up Drill', target: '4×50', muscles: 'freestyle timing', equip: 'pool', icon: '🤙', img: null, video: 'catch+up+drill+swimming',
          cues: 'One arm waits extended until the other completes a full stroke', mistake: 'Rushing the waiting arm', prog: 'Fix: rushing the pull' },
        { name: 'Fingertip Drag', target: '4×50', muscles: 'high-elbow recovery', equip: 'pool', icon: '🤙', img: null, video: 'fingertip+drag+drill',
          cues: 'Drag fingertips along the surface through recovery', mistake: 'Straight-arm swinging', prog: 'Fix: rushed, low recovery' },
        { name: 'Fist Drill', target: '2×50', muscles: 'forearm catch / feel', equip: 'pool', icon: '✊', img: null, video: 'fist+drill+swimming',
          cues: 'Swim with closed fists — forearm does the pulling', mistake: 'Dropping the elbow', prog: 'Open hands after — instant feedback' },
        { name: 'Single-Arm Free', target: '4×25/arm', muscles: 'stroke mechanics · rotation', equip: 'pool', icon: '🤙', img: null, video: 'single+arm+freestyle+drill',
          cues: 'One arm strokes, other extended in front', mistake: 'Flat hips, no rotation', prog: 'Extended → arm-at-side (advanced)' },
        { name: '6-Kick Switch', target: '4×50', muscles: 'side balance · rotation', equip: 'pool', icon: '🦶', img: null, video: '6+kick+switch+drill',
          cues: '6 kicks on the side, one stroke to rotate, repeat', mistake: 'Face forward instead of down', prog: 'Fix: balance & rotation' },
        { name: 'Sculling', target: '4×25', muscles: 'feel for the water', equip: 'pool (+buoy)', icon: '🖐️', img: null, video: 'sculling+drill+swimming',
          cues: 'Small figure-8 hand sweeps, face down, slow travel', mistake: 'Big paddling strokes', prog: 'Front scull → mid scull' },
        { name: 'Kickboard Kick Set', target: '4×50', muscles: 'legs · kick mechanics', equip: 'kickboard', icon: '🛹', img: null, video: 'kickboard+drills',
          cues: 'Steady flutter from the hips, hips near surface', mistake: 'Knee-driven bicycle kick', prog: 'Board → streamline kick on back' },
        { name: 'Pull Buoy Set', target: '4×75', muscles: 'upper-body pull', equip: 'pull buoy', icon: '🛟', img: null, video: 'pull+buoy+technique',
          cues: 'Buoy between thighs, no kick — pure catch & rotation', mistake: 'Snaking from no core tension', prog: 'Add paddles later (sparingly)' },
        { name: 'Streamline Glide + Kick', target: 'every wall', muscles: 'posture off walls', equip: 'pool', icon: '🚀', img: null, video: 'streamline+push+off',
          cues: 'Biceps behind ears, tight line, kick before surfacing', mistake: 'Surfacing immediately', prog: 'Add dolphin kicks underwater' },
        { name: 'Vertical Kicking', target: '4×20 s', muscles: 'kick power · core', equip: 'deep water', icon: '🕴️', img: null, video: 'vertical+kicking+drill',
          cues: 'Tread with flutter/dolphin only, arms crossed', mistake: 'Hands sneaking in', prog: '15 s → 30 s → weight overhead' },
      ]},
      { title: 'Example sessions', items: [
        { name: 'Easy Recovery Swim', target: '~30 min · 1200 m', muscles: 'active recovery (RPE 3–4)', equip: 'pool', icon: '🧘', img: null, video: 'easy+recovery+swim',
          cues: '200 easy · 4×50 drill · 6×100 easy free @ :20 rest · 4×25 back/breast · 100 easy', mistake: 'Letting it creep into a workout — keep it conversational', prog: 'Day after heavy legs or long run' },
        { name: 'Conditioning Swim', target: '~40 min · 1800 m', muscles: 'aerobic engine', equip: 'pool', icon: '🔥', img: null, video: 'swim+conditioning+workout',
          cues: '300 mix · 4×50 build @ 1:10 · 3×[2×100 @ 2:05 + 50 strong] · 4×75 pull · 150 easy', mistake: 'Sprinting the first round', prog: 'Descend 1–4 · shrink send-offs over weeks' },
      ]},
    ],
  },

  // ============================================================
  boxing: {
    label: 'Boxing',
    icon: '🥊',
    blurb: 'Numbers: odd = lead hand, even = rear. Classic combos: 1-2 · 1-1-2 · 1-2-3 · 2-3-2 · 1-2-3-2 · 1-2-5-2. Rounds: 3 min work / 1 min rest.',
    groups: [
      { title: 'Punches (1–6)', items: [
        { name: '1 · Jab', target: 'lead straight', muscles: 'shoulders · triceps · timing', equip: 'none', icon: '🥊', img: null, video: 'boxing+jab+technique',
          cues: 'Snap out from guard, fist rotates palm-down, straight back to the face', mistake: 'Lazy return — hand drops', prog: 'Mirror → bag → double jab' },
        { name: '2 · Cross', target: 'rear straight', muscles: 'hips · core rotation · triceps', equip: 'none', icon: '🥊', img: null, video: 'boxing+cross+technique',
          cues: 'Pivot the rear foot, rotate hips + shoulders, chin behind the shoulder', mistake: 'Arm-punching without hip rotation', prog: '1-2 rhythm on the bag' },
        { name: '3 · Lead Hook', target: 'lead bent-arm', muscles: 'obliques · lats · shoulders', equip: 'none', icon: '🥊', img: null, video: 'boxing+lead+hook+technique',
          cues: 'Elbow locked ~90°, pivot the lead foot (“squash the bug”), whole body turns', mistake: 'Winding up — telegraphs', prog: '1-2-3 flow' },
        { name: '4 · Rear Hook', target: 'rear bent-arm', muscles: 'rear-side rotation · glutes', equip: 'none', icon: '🥊', img: null, video: 'boxing+rear+hook',
          cues: 'Pivot hard on the rear foot; lead hand glued to the cheek', mistake: 'Squaring up, losing stance', prog: '2-3-4 on the pads' },
        { name: '5 · Lead Uppercut', target: 'lead upward', muscles: 'legs · biceps · core', equip: 'none', icon: '🥊', img: null, video: 'boxing+lead+uppercut',
          cues: 'Dip with the knees, drive UP through legs & hips, elbow stays bent', mistake: 'Dropping the hand to the waist first', prog: '1-2-5-2' },
        { name: '6 · Rear Uppercut', target: 'rear upward', muscles: 'posterior chain · hip extension', equip: 'none', icon: '🥊', img: null, video: 'boxing+rear+uppercut',
          cues: 'Load the rear side, rotate hips as the fist arcs up tight', mistake: 'Looping it wide like a hook', prog: '6-3-2 close-range combo' },
      ]},
      { title: 'Footwork & defense', items: [
        { name: 'Stance Check', target: 'daily 2 min', muscles: 'base position', equip: 'mirror', icon: '🧍', img: null, video: 'boxing+stance+basics',
          cues: 'Feet diagonal shoulder-width+, rear heel up, hands at cheeks, chin tucked', mistake: 'Feet on one line — no balance', prog: 'Hold stance through combos' },
        { name: 'Step-Drag', target: '3 min round', muscles: 'footwork base', equip: 'none', icon: '👣', img: null, video: 'boxing+step+drag+footwork',
          cues: 'Near foot steps first, trailing foot drags back to width; never cross', mistake: 'Hopping / feet clicking together', prog: 'Forward-back → lateral → with jab' },
        { name: 'Pivot', target: '3 min round', muscles: 'angles', equip: 'none', icon: '🌀', img: null, video: 'boxing+pivot+technique',
          cues: 'Rotate on the ball of the lead foot, rear foot swings around', mistake: 'Standing tall mid-pivot', prog: '10–15° → 90° → pivot after combos' },
        { name: 'Slip', target: '3×20', muscles: 'head movement', equip: 'none', icon: '↔️', img: null, video: 'boxing+slip+technique',
          cues: 'Small head shift off the line, bend knees + waist, eyes on target', mistake: 'Leaning instead of slipping — off balance', prog: 'Slip line/rope drill' },
        { name: 'Roll / Weave', target: '3×20', muscles: 'legs · core', equip: 'none', icon: '🌊', img: null, video: 'boxing+roll+under+technique',
          cues: 'Trace a “U” under the hook with the legs, come up ready to punch', mistake: 'Bending the back, not the knees', prog: 'Roll under a rope → 3-roll-3' },
        { name: 'Block / Parry', target: '3×20', muscles: 'guard skills', equip: 'none', icon: '🛡️', img: null, video: 'boxing+block+parry',
          cues: 'Glove glued to cheekbone to block; light open-hand tap to parry straights', mistake: 'Reaching for the parry', prog: 'Block → parry-counter (parry-2)' },
      ]},
      { title: 'Training methods', items: [
        { name: 'Shadowboxing', target: '3×3 min', muscles: 'technique · flow', equip: 'none', icon: '👤', img: null, video: 'shadow+boxing+workout',
          cues: 'Imagine a real opponent; move after every combo', mistake: 'Standing still throwing arms', prog: 'Theme rounds: footwork-only → defense-only → free' },
        { name: 'Heavy Bag', target: '4–6×3 min', muscles: 'power · conditioning', equip: 'bag + gloves', icon: '🥊', img: null, video: 'heavy+bag+workout+beginner',
          cues: 'Snap punches, don’t push; keep moving around the bag', mistake: 'Pushing the bag — no snap', prog: 'Jabs/1-2 → add hooks → add uppercuts → 15 s max bursts' },
        { name: 'Pad Work', target: '3×3 min', muscles: 'accuracy · reactions', equip: 'partner + mitts', icon: '🎯', img: null, video: 'boxing+pad+work+combos',
          cues: 'Listen for the numbers, reset to guard after every combo', mistake: 'Admiring your work — hands drop', prog: 'Set combos → coach-called → add defense between' },
        { name: 'Skipping Rope', target: '3×3 min', muscles: 'calves · rhythm · footwork', equip: 'rope', icon: '➰', img: 'Rope_Jumping', video: 'boxing+jump+rope+basics',
          cues: 'Balls of the feet, wrists spin the rope', mistake: 'Arms swinging wide', prog: 'Two-foot bounce → boxer skip → double-unders' },
        { name: 'Double-End Bag', target: '2–3×3 min', muscles: 'timing · accuracy', equip: 'double-end bag', icon: '🎯', img: null, video: 'double+end+bag+basics',
          cues: 'Start with single jabs, find the rhythm before combos', mistake: 'Swinging hard at a fast target', prog: 'Jab → 1-2 → slip + counter' },
        { name: 'Roadwork', target: '20–45 min', muscles: 'aerobic base', equip: 'shoes', icon: '🏃', img: 'Running_Treadmill', video: 'boxing+roadwork+training',
          cues: 'Mix steady runs with fartlek pace changes that mimic rounds', mistake: 'Only long slow miles', prog: 'LSD → fartlek → hill sprints' },
        { name: 'Conditioning Circuit', target: '3 min rounds · 40 s on/20 s off', muscles: 'full body · punching muscles', equip: 'bodyweight/med ball', icon: '🔥', img: 'Mountain_Climbers', video: 'boxing+conditioning+circuit',
          cues: 'Burpees · squats · push-ups · planks · med-ball slams at round pace', mistake: 'Pacing it like a stroll — keep round intensity', prog: 'Add rounds; shrink rests to :15' },
      ]},
    ],
  },

  // ============================================================
  muaythai: {
    label: 'Muay Thai',
    icon: '🦵',
    blurb: 'The art of eight limbs — fists (mat), elbows (sok), knees (khao), shins (te). Thai stance: more upright & square than boxing, weight ~60% on the rear leg so the lead leg stays light for checks and teeps. Rounds: 3 min / 1 min rest.',
    groups: [
      { title: 'Punches (mat) — Thai style', items: [
        { name: 'Jab (Mat Na)', target: '3×20', muscles: 'shoulders · timing · range', equip: 'bag/pads', icon: '🥊', img: null, video: 'muay+thai+jab+technique',
          cues: 'Snap from the taller Thai guard; often a range-finder for the kick behind it', mistake: 'Dropping the hand — Thai elbows punish it', prog: 'Jab → jab-teep → jab-kick' },
        { name: 'Cross (Mat Trong)', target: '3×20', muscles: 'hips · core rotation', equip: 'bag/pads', icon: '🥊', img: null, video: 'muay+thai+cross+technique',
          cues: 'Rear-foot pivot, hips through, chin behind the shoulder — stay upright for the counter kick', mistake: 'Over-leaning like a boxer — eats knees', prog: '1-2 → 1-2-low kick' },
        { name: 'Hook (Mat Wiang San)', target: '3×15/side', muscles: 'obliques · rotation', equip: 'bag/pads', icon: '🥊', img: null, video: 'muay+thai+hook+technique',
          cues: 'Elbow ~90°, pivot the foot, whole body turns; often follows a kick catch', mistake: 'Winding up — telegraphs', prog: 'Hook → hook-kick same side' },
        { name: 'Uppercut (Mat Soi)', target: '3×15/side', muscles: 'legs · core', equip: 'bag/pads', icon: '🥊', img: null, video: 'muay+thai+uppercut+technique',
          cues: 'Dip with the knees, drive up through the legs; great into the clinch entry', mistake: 'Big wind-up to the waist', prog: 'Uppercut → uppercut-knee' },
        { name: 'Overhand (Chok Dai)', target: '3×10', muscles: 'shoulder · full rotation', equip: 'bag/pads', icon: '🥊', img: null, video: 'muay+thai+overhand+punch',
          cues: 'Loop over the guard with a slight lean-off-line; body follows the punch', mistake: 'Falling forward after it', prog: 'After the opponent’s jab → as a kick counter' },
        { name: 'Spinning Backfist (Mat Wiang Klap)', target: '3×8/side', muscles: 'rotation · spatial awareness', equip: 'bag', icon: '🌀', img: null, video: 'spinning+backfist+technique',
          cues: 'Step across the centerline, LOOK over the shoulder first, whip the back of the fist through', mistake: 'Spinning blind / over-rotating', prog: 'Slow shadow → bag → off a missed kick' },
        { name: 'Superman Punch (Kradot Chok)', target: '3×8', muscles: 'explosiveness · deception', equip: 'bag', icon: '🦸', img: null, video: 'superman+punch+technique',
          cues: 'Fake the rear kick — as the leg chambers, kick it BACK and launch the cross forward', mistake: 'No kick fake first — just a lunging punch', prog: 'Shadow the fake → bag → after establishing the teep' },
      ]},
      { title: 'Elbows (sok)', items: [
        { name: 'Horizontal Elbow (Sok Tat)', target: '3×10/side', muscles: 'shoulders · core rotation', equip: 'pads/bag', icon: '💪', img: null, video: 'muay+thai+horizontal+elbow',
          cues: 'Slash across like a hook with the elbow point, palm down, step in — short-range weapon', mistake: 'Throwing from too far out', prog: 'Shadow → pad reps → in combos' },
        { name: 'Uppercut Elbow (Sok Ngat)', target: '3×10/side', muscles: 'legs · core extension', equip: 'pads/bag', icon: '💪', img: null, video: 'muay+thai+uppercut+elbow',
          cues: 'Drive the elbow tip straight up the centerline, rising through the legs', mistake: 'Leaning back and losing balance', prog: 'After the clinch break → in tight combos' },
        { name: 'Diagonal Elbow (Sok Ti)', target: '3×10/side', muscles: 'shoulders · obliques', equip: 'pads/bag', icon: '💪', img: null, video: 'muay+thai+diagonal+elbow+sok+ti',
          cues: 'Slash downward at ~45° through the target; short, sharp, close range', mistake: 'Arming it without body rotation', prog: 'Off the hook line → after a kick catch' },
        { name: 'Spinning Elbow (Sok Klap)', target: '3×6/side', muscles: 'rotational power · balance', equip: 'bag', icon: '🌀', img: null, video: 'muay+thai+spinning+elbow',
          cues: 'Step across, look over the shoulder before you turn, whip the rear elbow through', mistake: 'Spinning blind; over-rotating past the target', prog: 'Slow shadow → pad → as a counter when they circle' },
      ]},
      { title: 'Knees (khao)', items: [
        { name: 'Straight Knee (Khao Trong)', target: '3×10/leg', muscles: 'hip flexors · glutes · core', equip: 'bag', icon: '🦿', img: null, video: 'muay+thai+straight+knee+technique',
          cues: 'Drive the hips forward, point the knee like a spear, rise onto the ball of the support foot', mistake: 'Curling the leg up instead of thrusting the hips through', prog: 'Bag knees → clinch-pull knees → knee marathon' },
        { name: 'Diagonal Knee (Khao Chiang)', target: '3×10/leg', muscles: 'hips · obliques', equip: 'bag/pads', icon: '🦿', img: null, video: 'muay+thai+diagonal+knee',
          cues: 'Knee cuts in at ~45° around a guard, hips still drive through', mistake: 'Swinging the leg wide with no hip', prog: 'Straight knee first → diagonal off the clinch' },
        { name: 'Curving / Side Knee (Khao Khong)', target: '3×8/leg', muscles: 'hips · clinch control', equip: 'bag/partner', icon: '🦿', img: null, video: 'muay+thai+side+knee+clinch',
          cues: 'From the clinch, swing the knee around/over the opponent’s arm into ribs', mistake: 'Losing posture in the clinch to throw it', prog: 'Clinch posture first → add khao khong' },
        { name: 'Flying Knee (Khao Loi)', target: '3×6', muscles: 'explosiveness · full body', equip: 'bag', icon: '🚀', img: null, video: 'muay+thai+flying+knee',
          cues: 'Step-hop off the rear leg, drive the knee up as you rise, arms frame for safety', mistake: 'Jumping without the step rhythm — no height or power', prog: 'Skip knees → hop knees → full khao loi on the bag' },
      ]},
      { title: 'Kicks (te) & teeps', items: [
        { name: 'Roundhouse / Body Kick (Te Chiang)', target: 'sets of 10–25/leg', muscles: 'hips · glutes · obliques', equip: 'bag/pads', icon: '🦵', img: null, video: 'muay+thai+roundhouse+kick+technique',
          cues: 'Step out ~45°, pivot fully, swing the arm down for torque, strike with the SHIN and kick through', mistake: 'No pivot — kills power and strains the knee', prog: 'Slow-motion form → bag volume → power sets' },
        { name: 'Low Kick (Te Kha)', target: '3×10/leg', muscles: 'hips · balance', equip: 'bag/pads', icon: '🦵', img: null, video: 'muay+thai+low+kick+technique',
          cues: 'Roundhouse mechanics chopped down at thigh height, slight downward angle', mistake: 'Reaching without stepping into range', prog: 'Pad reps → bag power' },
        { name: 'Head Kick (Te Sung)', target: '3×6/leg', muscles: 'hips · flexibility', equip: 'bag/pads', icon: '🦵', img: null, video: 'muay+thai+head+kick+technique',
          cues: 'Same mechanics up top — needs hip mobility; set it up with low kicks and punches first', mistake: 'Throwing it cold with no setup (and no warm-up)', prog: 'Stretch + mid kicks → pad head kicks → in combos' },
        { name: 'Switch Kick', target: '3×8/leg', muscles: 'explosiveness · coordination', equip: 'bag/pads', icon: '⚡', img: null, video: 'muay+thai+switch+kick',
          cues: 'Small quick scissor-switch of the feet, then fire the lead-leg roundhouse instantly', mistake: 'Big slow telegraphed switch with a pause', prog: 'Shadow switch → pad reps → in combos' },
        { name: 'Lead Teep (Teep Trong)', target: '3×10/leg', muscles: 'hip flexors · balance', equip: 'bag', icon: '🦶', img: null, video: 'muay+thai+teep+technique',
          cues: 'Knee up first, stab out with a hip thrust, push with the ball of the foot, re-chamber', mistake: 'Leg-only push with no hip — falls forward after', prog: 'Wall balance teep → bag teep → teep the swinging bag' },
        { name: 'Rear Teep', target: '3×8/leg', muscles: 'hip drive · power', equip: 'bag', icon: '🦶', img: null, video: 'muay+thai+rear+teep',
          cues: 'More power, more telegraph — drive through the target as they step in', mistake: 'Slow chamber that gets caught', prog: 'Lead teep first → rear teep as a stopper' },
        { name: 'Question-Mark Kick', target: '3×6/leg', muscles: 'hips · deception', equip: 'pads', icon: '❓', img: null, video: 'question+mark+kick+technique',
          cues: 'Chamber like a teep/front kick, then whip it over the guard into a head kick', mistake: 'No fake first — reads as a slow head kick', prog: 'Teep + head kick solid first → blend them' },
      ]},
      { title: 'Defense & counters', items: [
        { name: 'Shin Check', target: 'every rhythm beat', muscles: 'balance · shin conditioning', equip: 'none', icon: '🛡️', img: null, video: 'muay+thai+check+kick',
          cues: 'Knee up and slightly out, foot relaxed, stay upright, hands in guard', mistake: 'Leaning back on the check', prog: 'Rhythm march + check → check + counter kick' },
        { name: 'Kick Catch & Sweep', target: '3×8/side', muscles: 'core · balance · timing', equip: 'partner/pads', icon: '🪝', img: null, video: 'muay+thai+kick+catch+counter',
          cues: 'Scoop the body kick, step in, kick out the standing leg or dump them off balance', mistake: 'Catching and standing still — counter immediately', prog: 'Catch → catch + sweep → catch + counter kick' },
        { name: 'Long Guard', target: '3×20 s', muscles: 'frame · defense', equip: 'partner/bag', icon: '🛡️', img: null, video: 'muay+thai+long+guard',
          cues: 'Lead arm extended into their face/shoulder, rear glove on your cheek — smothers punches at range', mistake: 'Reaching and leaning instead of framing', prog: 'Static frame → long guard + knee → + elbow off the frame' },
        { name: 'Jab–Cross–Kick (flow)', target: '3×3 min', muscles: 'full body flow', equip: 'bag/pads', icon: '🥊', img: null, video: 'muay+thai+basic+combos',
          cues: 'Punches set up kicks: 1-2 then step-out roundhouse; exhale sharply on every strike', mistake: 'Kicking without setting it up', prog: '1-2-kick → 1-2-3-low kick → add teep' },
      ]},
      { title: 'Movement & clinch', items: [
        { name: 'Thai Rhythm March + Check', target: '2×2 min', muscles: 'stance · shin block', equip: 'none', icon: '🧍', img: null, video: 'muay+thai+rhythm+check+kick',
          cues: 'Bounce in the lead-leg tapping rhythm; every 3rd beat lift a shin check — knee up and out, stay upright', mistake: 'Leaning back on the check', prog: 'March → check → check + counter kick' },
        { name: 'Clinch Pummeling', target: '2–3 min light', muscles: 'grip · neck · posture', equip: 'partner', icon: '🤼', img: null, video: 'muay+thai+clinch+pummeling+drill',
          cues: 'Swim an arm inside to steal inside position; stand tall, chin tucked, hips close', mistake: 'Bent-over posture — gets broken down', prog: 'Light continuous → add knees → add turns' },
        { name: 'Clinch Knees on Bag', target: '3×3 min', muscles: 'hips · grip endurance', equip: 'heavy bag', icon: '🦿', img: null, video: 'clinch+knees+heavy+bag',
          cues: 'Wrap the bag like a collar tie, pull it down and IN as the knee drives up, alternate with rhythm', mistake: 'All arm-pull, no hip drive', prog: '50 knees → 100 → 300 knee marathon' },
        { name: 'Thai Push-Ups', target: '3×8–12', muscles: 'chest · explosive push', equip: 'none', icon: '🫸', img: 'Pushups', video: 'explosive+push+ups',
          cues: 'Explosive push-up — hands leave the floor; land soft, elbows unlocked', mistake: 'Sagging hips on landing', prog: 'Regular → hands-off-floor → clapping' },
        { name: '200 Kicks Finisher', target: '100/leg on the bag', muscles: 'hips · lungs · will', equip: 'heavy bag', icon: '🔥', img: null, video: 'muay+thai+200+kicks+conditioning',
          cues: 'Sets of 25–50 roundhouses per leg, alternating; pace it — form degrades before lungs', mistake: 'Sloppy no-pivot kicks when tired', prog: '100 total → 200 → 300' },
      ]},
    ],
  },

  // ============================================================
  basketball: {
    label: 'Basketball',
    icon: '🏀',
    blurb: 'Handles, shooting and hoops athleticism. Condition with ≤60 s bursts at 1:2–1:3 work:rest. Train landing as hard as jumping — most knee injuries happen on landings.',
    groups: [
      { title: 'Skills', items: [
        { name: 'Pound Dribble Series', target: '30 s × 3 heights/hand', muscles: 'hand strength · control', equip: 'ball', icon: '🏀', img: null, video: 'pound+dribble+drill',
          cues: 'Dribble HARD at ankle, waist, shoulder height; eyes up', mistake: 'Watching the ball', prog: 'One ball → 2-ball pound → 2-ball alternating' },
        { name: 'Crossover Series', target: '20 reps/move', muscles: 'change of direction', equip: 'ball', icon: '🏀', img: null, video: 'crossover+dribble+series',
          cues: 'Snap the ball hip-to-hip below the knees; low stance', mistake: 'High, slow crossovers', prog: 'Crossover → between legs → behind back → combos' },
        { name: 'Figure-8 Dribble', target: '30 s/direction', muscles: 'tight low control', equip: 'ball', icon: '♾️', img: null, video: 'figure+8+dribble+drill',
          cues: 'Below knee height around and through the legs', mistake: 'Standing tall', prog: 'Walk it forward as you improve' },
        { name: 'Form Shooting', target: '25–50 makes', muscles: 'shot mechanics', equip: 'ball + hoop', icon: '🎯', img: null, video: 'form+shooting+drill',
          cues: '3–5 ft from rim, elbow aligned, hold the follow-through, aim swish', mistake: 'Backing up before the form is clean', prog: 'One-hand close → add guide hand → step back' },
        { name: 'Spot Shooting (5 spots)', target: '10 makes/spot', muscles: 'game-range accuracy', equip: 'ball + hoop', icon: '🎯', img: null, video: 'five+spot+shooting+drill',
          cues: 'Baseline–wing–top–wing–baseline; step INTO each shot', mistake: 'Drifting on the catch', prog: 'Comfortable range → 3-pt line' },
        { name: 'Mikan Drill', target: '2×10–20 makes', muscles: 'soft touch · both hands', equip: 'ball + hoop', icon: '🔄', img: null, video: 'mikan+drill',
          cues: 'Alternate R/L baby hooks off the backboard non-stop under the rim', mistake: 'Dropping the ball low between reps', prog: 'Mikan → reverse Mikan → power layups' },
        { name: 'Free Throws (fatigued)', target: '25–50, track %', muscles: 'routine under fatigue', equip: 'ball + hoop', icon: '🎯', img: null, video: 'free+throw+routine',
          cues: 'Same routine every rep; shoot in pairs like games', mistake: 'Machine-gunning without routine', prog: 'Fresh → after conditioning' },
        { name: 'Full-Court Layup Conditioning', target: '8–10 finishes × 3', muscles: 'game shape + finishing', equip: 'court', icon: '🏃', img: null, video: 'full+court+layup+conditioning',
          cues: 'Dribble full court at speed, finish, sprint back, finish the other end; alternate hands', mistake: 'Coasting the middle third', prog: 'Add rounds; add euro-step finishes' },
        { name: '17s / Suicides', target: '3 sets', muscles: 'anaerobic repeat sprints', equip: 'court', icon: '💨', img: null, video: 'basketball+17s+conditioning+drill',
          cues: '17 sideline-to-sideline in ≤ 65–70 s (or liners: FT → half → far FT → full)', mistake: 'Slowing the touches at the lines', prog: '1:3 rest → 1:2 rest' },
      ]},
      { title: 'Athleticism', items: [
        { name: 'Box Jump', target: '3×5', muscles: 'hips · quads · calves', equip: 'box', icon: '📦', img: 'Front_Box_Jump', video: 'box+jump+technique',
          cues: 'Big arm swing, land QUIETLY in a quarter squat on the box, step down', mistake: 'Jumping down off the box', prog: 'Pogo hops → box jump → depth drop → depth jump' },
        { name: 'Depth Jump', target: '3×5', muscles: 'reactive power · tendons', equip: '30–45 cm box', icon: '⚡', img: 'Depth_Jump_Leap', video: 'depth+jump+technique',
          cues: 'Step off, minimal ground time, explode straight up', mistake: 'Long soggy ground contact', prog: 'Depth drop (stick it) → depth jump — only after box jumps are easy' },
        { name: 'Lateral Bound', target: '3×5/side', muscles: 'glutes · adductors', equip: 'none', icon: '↔️', img: 'Lateral_Bound', video: 'lateral+bound+exercise',
          cues: 'Jump sideways, stick each landing 2 s, knee tracks over toes', mistake: 'Knee caving on the landing', prog: 'Stick → continuous → for distance' },
        { name: 'Snap-Down Landing', target: '3×5 every warm-up', muscles: 'landing mechanics', equip: 'none', icon: '🦵', img: null, video: 'snap+down+landing+drill',
          cues: 'From tall, snap into an athletic quarter squat — quiet feet, knees out', mistake: 'Loud flat-foot landings', prog: 'Snap-down → box-drop stick → single-leg stick' },
        { name: 'Copenhagen Plank', target: '2–3×10–20 s/side', muscles: 'adductors · groin', equip: 'bench', icon: '🧱', img: null, video: 'copenhagen+plank',
          cues: 'Side plank, top leg on the bench, hips tall', mistake: 'Hips sagging', prog: 'Knee on bench → full leg → lift bottom leg' },
        { name: 'Tibialis + Calf Wall Raises', target: '3×15 each', muscles: 'shins · calves', equip: 'wall', icon: '🦶', img: 'Standing_Calf_Raises', video: 'tibialis+raise+exercise',
          cues: 'Toes-up against wall lean; then full calf raises, slow lowering', mistake: 'Bouncing', prog: 'Two-leg → single-leg' },
      ]},
    ],
  },

  // ============================================================
  volleyball: {
    label: 'Volleyball',
    icon: '🏐',
    blurb: 'Skills + jump power + shoulder durability for weekly game night. Plyo cap ~80–120 contacts, 2×/week — game night counts as one. Land quiet, knees over toes.',
    groups: [
      { title: 'Skills', items: [
        { name: 'Wall Pass', target: '3×25 clean', muscles: 'platform control', equip: 'ball + wall', icon: '🏐', img: null, video: 'volleyball+wall+passing+drill',
          cues: 'Flat still platform, angle — don’t swing; back up as you improve', mistake: 'Swinging the arms at the ball', prog: 'Wall → partner pass → freeze pass' },
        { name: 'Wall Sets', target: '3×30', muscles: 'hand shape · quick release', equip: 'ball + wall', icon: '🙌', img: null, video: 'volleyball+wall+setting+drill',
          cues: 'Ball-shaped hands above the forehead, push with the legs', mistake: 'Catching/carrying the ball', prog: 'Close wall → step back → self-set to target' },
        { name: 'Float Serve', target: '20 tosses + 15 serves', muscles: 'toss consistency · contact', equip: 'ball', icon: '🎯', img: null, video: 'float+serve+technique',
          cues: 'Low toss in front of the hitting shoulder; firm hand, NO wrist snap', mistake: 'Wandering toss — chase the toss, miss the serve', prog: 'Toss-only reps → serve → target zones (5-in-a-row)' },
        { name: '3-Step Approach', target: '3×8', muscles: 'attack footwork', equip: 'none', icon: '👣', img: null, video: 'volleyball+3+step+approach+footwork',
          cues: '(Righty) L-R-L, slow-to-fast, big penultimate braking step, arms swing back then UP', mistake: 'Even-tempo steps — no acceleration', prog: '3-step → 4-step → full approach jumps to a wall target' },
        { name: 'Arm Swing Mechanics', target: '3×12', muscles: 'healthy spiking arm', equip: 'ball + wall', icon: '💪', img: null, video: 'volleyball+arm+swing+mechanics',
          cues: 'Bow-and-arrow draw, elbow high, contact IN FRONT of the shoulder, relaxed follow-through', mistake: 'Contact behind the head — shoulder killer', prog: 'Snap throws → standing wall hits → full approach hits' },
        { name: 'Block Footwork', target: '4×30 s', muscles: 'lateral speed · net play', equip: 'net/line', icon: '🧱', img: null, video: 'volleyball+blocking+footwork',
          cues: 'Shuffle 2 steps, jump, press hands OVER the net plane, land, shuffle back', mistake: 'Swatting down into the net', prog: 'Shuffle → 3-step crossover → live blocking' },
        { name: 'Base + Dig Reactions', target: '3×10 digs', muscles: 'defense · reactions', equip: 'partner', icon: '🛡️', img: null, video: 'volleyball+digging+drills',
          cues: 'Low wide base, weight forward; dig to target, recover to base every rep', mistake: 'Standing up between reps', prog: 'Tossed → hit at you → random direction' },
        { name: 'Pre-Game Warm-Up', target: '15 min', muscles: 'game prep', equip: 'ball + partner', icon: '🔥', img: null, video: 'volleyball+pregame+warmup',
          cues: 'Dynamic moves → shoulder ramp-up → pepper building to full speed → 4–6 approach jumps + 8 serves', mistake: 'Hitting cold at full power', prog: 'Same routine every game night' },
      ]},
      { title: 'Jump & durability', items: [
        { name: 'Approach Jump', target: '3×5–8 max', muscles: 'full spike-jump pattern', equip: 'wall target', icon: '⬆️', img: null, video: 'volleyball+approach+jump',
          cues: 'Full 3–4 step approach to max touch; measure it and chase it', mistake: 'No arm swing contribution', prog: 'After strength + box-jump base is built' },
        { name: 'Pogo Hops', target: '3×15', muscles: 'ankle stiffness · elastic return', equip: 'none', icon: '🦘', img: null, video: 'pogo+hops+exercise',
          cues: 'Stiff ankles, minimal knee bend, bounce like a spring', mistake: 'Deep knee bend each hop', prog: 'In place → line hops → box jumps' },
        { name: 'Box Jump', target: '3×5–8', muscles: 'hips · quads', equip: 'box', icon: '📦', img: 'Front_Box_Jump', video: 'box+jump+technique',
          cues: 'Big arm swing, land quiet in a quarter squat, step down', mistake: 'Loud caved-knee landings', prog: 'Box → depth jump (wk 6+) → approach jumps' },
        { name: 'Rear-Foot-Elevated Split Squat', target: '2–3×6–8/leg', muscles: 'single-leg power', equip: 'bench + DBs', icon: '🦵', img: 'Split_Squat_with_Dumbbells', video: 'bulgarian+split+squat+form',
          cues: 'Vertical front shin, slight forward lean, no knee cave', mistake: 'Pushing off the back foot', prog: 'Bodyweight → +DBs' },
        { name: 'Band External Rotation', target: '2–3×12–15', muscles: 'rotator cuff', equip: 'band', icon: '🛡️', img: 'External_Rotation_with_Band', video: 'band+external+rotation+shoulder',
          cues: 'Elbow pinned, rotate the forearm out SLOWLY; do the 90° version too (hitting position)', mistake: 'Fast sloppy reps', prog: 'At side → 90° abducted → cable' },
        { name: 'Face Pull + YTW', target: '2–3×12 + 2×8/letter', muscles: 'rear delts · lower traps', equip: 'band/bench', icon: '🛡️', img: 'Face_Pull', video: 'face+pull+ytw+shoulder+health',
          cues: 'Pull to the face, elbows high, finish rotated out; YTW slow with thumbs up', mistake: 'Shrugging into the neck', prog: '2×/week keeps the spiking shoulder healthy' },
        { name: 'Single-Leg RDL + Balance', target: '2×8/side + 30 s', muscles: 'hamstrings · ankle stability', equip: 'DB optional', icon: '🦶', img: null, video: 'single+leg+rdl+form',
          cues: 'Flat back hinge, reach, stand tall; then balance 30 s (eyes closed = harder)', mistake: 'Hips opening sideways', prog: 'Bodyweight → +DB → eyes-closed balance' },
      ]},
    ],
  },
};

// ============================================================
// Anatomy reference (info-only tab)
// ============================================================
const LIB_ANATOMY = {
  muscles: [
    { name: 'Pecs (chest)', where: 'Front of chest', does: 'Push arm forward/across', ex: 'Bench press · push-up · fly' },
    { name: 'Lats', where: 'Broad mid/lower back', does: 'Pull arm down/back', ex: 'Pull-up · pulldown · row' },
    { name: 'Traps', where: 'Neck → mid-back', does: 'Shrug, pull blades back/down', ex: 'Shrug · face pull · carries' },
    { name: 'Rhomboids', where: 'Between shoulder blades', does: 'Squeeze blades together', ex: 'Row · reverse fly' },
    { name: 'Delts (3 heads)', where: 'Shoulder cap', does: 'Raise arm front/side/rear', ex: 'OHP · lateral raise · reverse fly' },
    { name: 'Biceps', where: 'Front upper arm', does: 'Bend elbow, turn palm up', ex: 'Curl · chin-up · row' },
    { name: 'Triceps', where: 'Back upper arm', does: 'Straighten elbow', ex: 'Dip · pushdown · close-grip press' },
    { name: 'Forearms / grip', where: 'Elbow → wrist', does: 'Grip, wrist motion', ex: 'Dead hang · farmers carry' },
    { name: 'Abs (rectus)', where: 'Front of trunk', does: 'Curl spine, brace', ex: 'Crunch · hanging leg raise' },
    { name: 'Obliques', where: 'Sides of waist', does: 'Rotate / side-bend / resist both', ex: 'Pallof press · side plank · wood-chop' },
    { name: 'Deep core (TVA)', where: 'Deep belly wrap', does: 'Pressure + spine stability', ex: 'Plank · dead bug' },
    { name: 'Erector spinae', where: 'Along the spine', does: 'Keep back upright / extend', ex: 'Deadlift · back extension' },
    { name: 'Glute max', where: 'Butt', does: 'Drive hips forward', ex: 'Squat · hip thrust · sprint' },
    { name: 'Glute med', where: 'Side of hip', does: 'Stabilize pelvis on one leg', ex: 'Band walk · single-leg work' },
    { name: 'Quads', where: 'Front thigh', does: 'Straighten knee', ex: 'Squat · lunge · leg extension' },
    { name: 'Hamstrings', where: 'Back thigh', does: 'Bend knee + drive hips', ex: 'RDL · leg curl · Nordic' },
    { name: 'Adductors', where: 'Inner thigh', does: 'Pull leg inward, stabilize', ex: 'Sumo squat · Copenhagen plank' },
    { name: 'Calves (gastroc/soleus)', where: 'Back lower leg', does: 'Point the foot, push off', ex: 'Standing & seated calf raise' },
    { name: 'Hip flexors', where: 'Front of hip', does: 'Lift the knee', ex: 'Leg raise · L-sit · sprint knees' },
  ],
  pairs: [
    ['Chest ↔ Back', 'Press without pulling → rounded shoulders. Row as much as you press.'],
    ['Quads ↔ Hamstrings', 'Weak hamstrings raise knee/ACL risk. Hinge as much as you squat.'],
    ['Abs ↔ Lower back', 'Front-and-back core keeps the spine safe under load.'],
    ['Front ↔ Rear delts', 'Rear-delt work fixes pressing/desk posture.'],
    ['Hip flexors ↔ Glutes', 'Sitting tightens flexors + sleeps glutes — train the bridge/thrust.'],
    ['Biceps ↔ Triceps', 'Balanced elbow strength, healthy tracking.'],
  ],
  adapt: [
    ['Strength', '1–5 reps · heavy (≥80% max) · rest 2–5 min. Teaches the nervous system to produce force.'],
    ['Muscle (hypertrophy)', '~6–12+ reps near failure. Volume is king: ~10–20 hard sets per muscle per week, split over 2+ sessions.'],
    ['Endurance', '15+ reps light. Modest, mostly lower-body carryover.'],
    ['Progressive overload', 'Add weight, reps or sets over time — no increase, no adaptation.'],
    ['Recovery', 'Muscle rebuilds for ~24–48 h after training. Hit each muscle hard ~every 48–72 h → ~2×/week beats 1×.'],
    ['Mind–muscle', 'On isolation moves, focusing on the muscle can boost growth. On heavy compounds, focus on moving the bar.'],
  ],
};
