// library-data.js — curated training catalogs for the Exercise Library.
// Built from researched sources (HYROX rulebook/RoxLyfe, r/bodyweightfitness RR +
// Overcoming Gravity standards, Stronger by Science, USMS/MySwimPro, boxing
// coaching refs, NSCA/ACSM-aligned anatomy). Loaded before library.js.
//
// Entry: { name, target, muscles, equip, cues, mistake, prog, img (free-exercise-db
// id or null), icon, video (YouTube search terms) }
// Ladder: { name, trains, icon, video, steps: [{ name, std }] } — std = advance rule.

const LIB_TRAINING = {

  // ============================================================
  hyrox: {
    label: 'Hyrox',
    icon: '🏃',
    blurb: 'The 8 race stations (Men’s Open weights) + the standard prep movements. Race = 8×1 km runs, one station after each.',
    groups: [
      { title: 'Race stations', items: [
        { name: 'SkiErg', target: '1000 m', muscles: 'lats · triceps · core', equip: 'SkiErg', icon: '🎿', img: 'Straight-Arm_Pulldown', video: 'skierg+technique+hyrox',
          cues: 'Full-body “crunch” from hips + lats, long strokes ~35–45 spm', mistake: 'Sprinting the first 250 m — spikes HR before the sleds', prog: 'Build 400 m → 1000 m, then chase pace' },
        { name: 'Sled Push', target: '50 m · 152 kg', muscles: 'quads · glutes · calves', equip: 'sled', icon: '🛷', img: 'Sled_Push', video: 'hyrox+sled+push+technique',
          cues: 'Low ~45° body angle, short powerful steps, keep it moving', mistake: 'Standing too upright — kills force transfer', prog: 'Sub: heavy leg-press clusters · DB march · plate push on turf' },
        { name: 'Sled Pull', target: '50 m · 103 kg', muscles: 'lats · biceps · grip · posterior chain', equip: 'sled + rope', icon: '🪝', img: 'Sled_Row', video: 'hyrox+sled+pull+technique',
          cues: 'Stay low, lean back, hand-over-hand with constant rope tension', mistake: 'Arms-only pulling — fries grip before farmers carry', prog: 'Sub: heavy seated cable rows · towel-plate backward drags' },
        { name: 'Burpee Broad Jumps', target: '80 m', muscles: 'full body', equip: 'none', icon: '🤸', img: 'Standing_Long_Jump', video: 'burpee+broad+jump+form',
          cues: 'Chest to floor, feet together on the jump, modest ~1 m hops, steady rhythm', mistake: 'Max jumps early — torches the quads', prog: 'Knees-up standing is legal; 40 m → 80 m' },
        { name: 'RowErg', target: '1000 m', muscles: 'posterior chain · lats', equip: 'rower', icon: '🚣', img: 'Rowing_Stationary', video: 'rowerg+technique+hyrox',
          cues: 'Legs–body–arms, ~22–28 spm; this is your recovery station', mistake: 'Pulling a 2k-PR split — costs minutes later', prog: 'Build 400 m → 1000 m at controlled split' },
        { name: 'Farmers Carry', target: '200 m · 2×24 kg', muscles: 'grip · traps · core', equip: 'kettlebells/DBs', icon: '🧳', img: 'Farmers_Walk', video: 'farmers+carry+technique',
          cues: 'Tall posture, shoulders packed, quick short steps', mistake: 'Setting the bells down — each drop costs 10–15 s', prog: 'Heavier DBs, fewer breaks; 2×16 → 2×24 kg' },
        { name: 'Sandbag Lunges', target: '100 m · 20 kg', muscles: 'quads · glutes · hamstrings', equip: 'sandbag', icon: '🦵', img: 'Dumbbell_Rear_Lunge', video: 'sandbag+walking+lunge',
          cues: 'Bag high on traps, chest up, rear knee touches every rep', mistake: 'Leaning forward under the bag — loads the lower back', prog: 'Sub: goblet/back-rack walking lunges; 8 → 20 kg' },
        { name: 'Wall Balls', target: '100 reps · 6 kg → 3 m', muscles: 'quads · glutes · shoulders', equip: 'med ball', icon: '🏐', img: 'Medicine_Ball_Scoop_Throw', video: 'wall+ball+shot+form',
          cues: 'Full squat, one throw–catch–ride-down rhythm; break early on purpose (25/25/25/25)', mistake: 'Missing the 3 m target when tired — no-reps', prog: 'Sub: DB thrusters · med-ball throw-ups; 40 → 100 reps' },
      ]},
      { title: 'Prep movements', items: [
        { name: 'Kettlebell Swing', target: '3×15', muscles: 'glutes · hamstrings · grip', equip: 'kettlebell', icon: '🏋️', img: 'One-Arm_Kettlebell_Swings', video: 'kettlebell+swing+form',
          cues: 'Hinge not squat; snap the hips, arms are ropes', mistake: 'Squatting the swing', prog: 'Deadlift-to-stand → swing → heavier bell' },
        { name: 'Weighted Step-Up', target: '3×8/leg', muscles: 'quads · glutes', equip: 'box + DBs', icon: '🦵', img: 'Dumbbell_Step_Ups', video: 'dumbbell+step+up+form',
          cues: 'Full foot on box, drive without pushing off the back leg', mistake: 'Bouncing off the rear leg', prog: 'Low box → knee height → +DBs' },
        { name: 'Dead-Ball Over Shoulder', target: '3×8', muscles: 'posterior chain', equip: 'dead ball/sandbag', icon: '🏐', img: null, video: 'dead+ball+over+shoulder',
          cues: 'Hips under, lap the ball, extend and throw over the shoulder', mistake: 'Rounding the back on the pick', prog: 'Light ball → race-weight sandbag' },
        { name: 'Assault Bike Intervals', target: '10×45 s hard / 75 s easy', muscles: 'full body', equip: 'air bike', icon: '🚴', img: 'Bicycling_Stationary', video: 'assault+bike+intervals',
          cues: 'Big gears with legs, steady pull with arms', mistake: 'All-out first interval', prog: 'Add intervals or shrink the rest' },
        { name: 'Goblet Squat', target: '3×12', muscles: 'quads · core', equip: 'KB/DB', icon: '🏋️', img: 'Goblet_Squat', video: 'goblet+squat+form',
          cues: 'Elbows inside knees, full depth, heels down', mistake: 'Heels lifting', prog: 'Bodyweight → goblet → double-KB front squat' },
        { name: 'Romanian Deadlift', target: '3×10', muscles: 'hamstrings · glutes', equip: 'barbell/DBs', icon: '🏋️', img: 'Romanian_Deadlift', video: 'romanian+deadlift+form',
          cues: 'Soft knees, hips back, flat back to mid-shin', mistake: 'Squatting the hinge', prog: 'Hinge drill → RDL → single-leg RDL' },
        { name: 'Weighted-Vest Run', target: '4×400 m race pace', muscles: 'legs · aerobic system', equip: '5–10 kg vest', icon: '🏃', img: 'Running_Treadmill', video: 'weighted+vest+running',
          cues: 'Short race-pace reps only, tall posture', mistake: 'Long slow vest runs — joint stress, little gain', prog: 'Add reps before adding vest weight' },
        { name: 'Compromised-Run Brick', target: '4–6×(1 km + station)', muscles: 'full body', equip: 'varies', icon: '🧱', img: null, video: 'hyrox+compromised+running',
          cues: 'Station → run at goal pace; find your legs within 200 m', mistake: 'Standing rest between station and run', prog: 'Classic brick → station sandwich → half-Hyrox sim' },
      ]},
    ],
  },

  // ============================================================
  calisthenics: {
    label: 'Calisthenics',
    icon: '🤸',
    blurb: 'Skill ladders, easiest → hardest. Rule: hit 3×8 clean reps (or 3×20–30 s hold) → move up a step and restart at 3×5. Can’t get 3×5 → move down.',
    ladders: [
      { name: 'Push-Up Ladder', trains: 'chest · front delts · triceps · core', icon: '🫸', video: 'push+up+progression', img: 'Pushups',
        steps: [
          { name: 'Wall push-up', std: '3×15' }, { name: 'Incline push-up', std: '3×8–12' }, { name: 'Knee push-up', std: '3×10–15' },
          { name: 'Full push-up', std: '3×8 clean' }, { name: 'Diamond push-up', std: '3×8' }, { name: 'Decline push-up', std: '3×8' },
          { name: 'Pseudo-planche push-up', std: '3×8 moderate lean' }, { name: 'Archer push-up', std: '3×6/side' }, { name: 'One-arm progressions', std: '3×5/side per stage' },
        ]},
      { name: 'Pull-Up Ladder', trains: 'lats · biceps · scapular control · grip', icon: '🫷', video: 'pull+up+progression', img: 'Pullups',
        steps: [
          { name: 'Dead hang', std: '3×30–60 s' }, { name: 'Scapular pulls', std: '3×8' }, { name: 'Negatives (3–5 s down)', std: '3×5–8' },
          { name: 'Band-assisted pull-up', std: '3×8 lightest band' }, { name: 'Full pull-up', std: '3×8' }, { name: 'Chest-to-bar', std: '3×6–8' },
          { name: 'Archer pull-up', std: '3×5/side' }, { name: 'Typewriter pull-up', std: '3×4–6/side' }, { name: 'Weighted pull-up', std: '3×5 @ +10–15% BW' },
          { name: 'Muscle-up transition negatives', std: '3×3–5 slow' },
        ]},
      { name: 'Dip Ladder', trains: 'lower chest · triceps · front delts', icon: '💪', video: 'dip+progression', img: 'Dips_-_Triceps_Version',
        steps: [
          { name: 'Support hold', std: '3×30 s' }, { name: 'Bench dips', std: '3×10–12' }, { name: 'Dip negatives (3–5 s)', std: '3×5–8' },
          { name: 'Parallel-bar dips', std: '3×8' }, { name: 'Ring dips', std: '3×8' }, { name: 'Weighted dips', std: 'load at 3×5–8' },
        ]},
      { name: 'Squat Ladder', trains: 'quads · glutes · balance · ankle mobility', icon: '🦵', video: 'pistol+squat+progression', img: 'Bodyweight_Squat',
        steps: [
          { name: 'Assisted squat', std: '3×10–15' }, { name: 'Bodyweight squat', std: '3×15–20' }, { name: 'Split squat', std: '3×8/side' },
          { name: 'Bulgarian split squat', std: '3×8/side' }, { name: 'Shrimp squat', std: '3×6–8/side' }, { name: 'Assisted pistol', std: '3×6/side' },
          { name: 'Full pistol squat', std: '3×5/side clean' },
        ]},
      { name: 'Handstand Ladder', trains: 'shoulders · traps · wrists · balance', icon: '🤸', video: 'handstand+progression', img: 'Handstand_Push-Ups',
        steps: [
          { name: 'Wall plank / pike hold', std: '3×30–60 s' }, { name: 'Wall walk', std: '3×3–5 walks' }, { name: 'Chest-to-wall hold', std: '1×60 s' },
          { name: 'Kick-up practice', std: '5–10 s balance touches' }, { name: 'Freestanding handstand', std: '10–20 s consistent' },
          { name: 'Pike push-up', std: '3×8' }, { name: 'Wall HSPU negatives', std: '3×5' }, { name: 'Wall HSPU', std: '3×5 full ROM' },
        ]},
      { name: 'L-Sit Ladder', trains: 'hip flexors · abs · triceps · compression', icon: '🪑', video: 'l+sit+progression', img: null,
        steps: [
          { name: 'Foot-supported L-sit', std: '3×20–30 s' }, { name: 'Tuck L-sit', std: '3×20–30 s' }, { name: 'One-leg L-sit', std: '3×10–15 s/leg' },
          { name: 'Full L-sit', std: '3×10–20 s' }, { name: 'V-sit', std: '3×5–10 s per angle' },
        ]},
      { name: 'Front Lever Ladder', trains: 'lats · core anti-extension · straight-arm pull', icon: '🦇', video: 'front+lever+progression', img: null,
        steps: [
          { name: 'Tuck front lever', std: '3×20–30 s' }, { name: 'Advanced tuck', std: '3×15–20 s' }, { name: 'One-leg front lever', std: '3×10–15 s/side' },
          { name: 'Straddle front lever', std: '3×8–12 s' }, { name: 'Full front lever', std: '3×5–10 s' },
        ]},
      { name: 'Back Lever Ladder', trains: 'chest · front delts · biceps tendons (go slow!)', icon: '🦇', video: 'back+lever+progression', img: null,
        steps: [
          { name: 'Tuck back lever', std: '3×20–30 s' }, { name: 'Advanced tuck', std: '3×15–20 s' }, { name: 'One-leg back lever', std: '3×10–15 s/side' },
          { name: 'Straddle back lever', std: '3×8–12 s' }, { name: 'Full back lever', std: '3×5–10 s' },
        ]},
      { name: 'Core: Plank → Ab Wheel', trains: 'anti-extension core', icon: '🧱', video: 'ab+wheel+progression', img: 'Ab_Roller',
        steps: [
          { name: 'Plank', std: '60 s clean' }, { name: 'RKC plank (max tension)', std: '3×10–20 s' }, { name: 'Kneeling rollout', std: '3×8' },
          { name: 'Partial standing rollout', std: '3×8' }, { name: 'Full standing ab-wheel rollout', std: '3×8' },
        ]},
      { name: 'Core: Hollow → Dragon Flag', trains: 'abs · full-body tension', icon: '🐉', video: 'dragon+flag+progression', img: null,
        steps: [
          { name: 'Hollow-body hold', std: '30 s perfect' }, { name: 'Tuck dragon flag', std: '3×6–8' }, { name: 'Single-leg dragon flag', std: '3×5–6' },
          { name: 'Full dragon flag', std: '3×5 controlled' },
        ]},
    ],
  },

  // ============================================================
  home: {
    label: 'Home',
    icon: '🏠',
    blurb: 'Minimal-kit training. Hypertrophy and beginner→intermediate strength are fully trainable at home; max-strength barbell work isn’t. Sub table per gym lift is inside each card.',
    groups: [
      { title: 'Top home exercises', items: [
        { name: 'Push-Up', target: '3×AMRAP−2', muscles: 'chest · triceps · delts', equip: 'none', icon: '🫸', img: 'Pushups', video: 'push+up+form',
          cues: 'Rigid plank; elbows ~45°', mistake: 'Sagging hips', prog: 'Incline → floor → deficit/weighted' },
        { name: 'Pike Push-Up', target: '3×8', muscles: 'shoulders · triceps', equip: 'none', icon: '🤸', img: null, video: 'pike+push+up+form',
          cues: 'Hips high; head travels ahead of hands', mistake: 'Turning it into a push-up', prog: 'Pike → feet-elevated → wall HSPU' },
        { name: 'Pull-Up', target: '3×5–8', muscles: 'lats · biceps', equip: 'bar', icon: '🫷', img: 'Pullups', video: 'pull+up+form',
          cues: 'Dead-hang start; chest to bar', mistake: 'Kipping / partial range', prog: 'Band-assisted → strict → weighted (backpack)' },
        { name: 'Inverted Row', target: '3×8–12', muscles: 'mid-back · biceps', equip: 'table/rings', icon: '🫷', img: 'Inverted_Row', video: 'inverted+row+form',
          cues: 'Straight body; squeeze the blades', mistake: 'Hips dropping', prog: 'Bent knees → straight → feet elevated' },
        { name: 'Goblet Squat', target: '3×8–12', muscles: 'quads · glutes', equip: 'DB/KB', icon: '🦵', img: 'Goblet_Squat', video: 'goblet+squat+form',
          cues: 'Elbows inside knees; heels down', mistake: 'Heels lifting', prog: 'Bodyweight → goblet → double-KB front squat' },
        { name: 'Bulgarian Split Squat', target: '3×8/leg', muscles: 'quads · glutes', equip: 'chair (+DBs)', icon: '🦵', img: 'Split_Squat_with_Dumbbells', video: 'bulgarian+split+squat+form',
          cues: 'Slight forward lean; knee tracks toes', mistake: 'Pushing off the back foot', prog: 'Split squat → rear-foot-elevated → +DBs (subs for back squat)' },
        { name: 'DB Romanian Deadlift', target: '3×10', muscles: 'hamstrings · glutes', equip: 'DBs/KB', icon: '🏋️', img: 'Romanian_Deadlift', video: 'dumbbell+romanian+deadlift',
          cues: 'Hips back; flat back', mistake: 'Squatting the hinge', prog: 'Hinge drill → RDL → single-leg RDL (subs for deadlift)' },
        { name: 'KB Swing', target: '3×15', muscles: 'glutes · hamstrings', equip: 'KB', icon: '🏋️', img: 'One-Arm_Kettlebell_Swings', video: 'kettlebell+swing+form',
          cues: 'Hike, snap hips; arms relaxed', mistake: 'Squat-and-lift, no hinge', prog: 'Deadlift-to-stand → swing → single-arm' },
        { name: 'Slider Leg Curl', target: '3×8', muscles: 'hamstrings', equip: 'towel/sliders', icon: '🦵', img: null, video: 'slider+leg+curl',
          cues: 'Hips high; ribs down', mistake: 'Hips drop as legs extend', prog: 'Glute bridge → sliders → eccentric Nordic → full Nordic (subs for leg curl)' },
        { name: 'DB Hip Thrust', target: '3×10', muscles: 'glutes', equip: 'couch + DB', icon: '🍑', img: 'Barbell_Hip_Thrust', video: 'dumbbell+hip+thrust',
          cues: 'Chin tucked; vertical shin at lockout', mistake: 'Hyperextending the spine', prog: 'Bridge → thrust → single-leg +DB' },
        { name: 'Step-Up', target: '3×8/leg', muscles: 'quads · glutes', equip: 'step + DBs', icon: '🦵', img: 'Dumbbell_Step_Ups', video: 'step+up+form',
          cues: 'Full foot on step; minimal push-off', mistake: 'Bouncing off the back leg', prog: 'Low box → knee height → +DBs' },
        { name: 'Single-Leg Calf Raise', target: '3×15/leg', muscles: 'calves', equip: 'step', icon: '🦶', img: 'Standing_Calf_Raises', video: 'single+leg+calf+raise',
          cues: 'Full stretch; 2 s pause at top', mistake: 'Bouncing', prog: 'Two-leg → single → +DB' },
        { name: 'DB Floor Press', target: '3×8', muscles: 'chest · triceps', equip: 'DBs', icon: '🫸', img: null, video: 'dumbbell+floor+press',
          cues: 'Wrists over elbows; light arm touch on floor', mistake: 'Flaring elbows to 90°', prog: 'Two-DB → single-arm → slow eccentric (subs for bench)' },
        { name: 'Single-Arm DB Row', target: '3×10/arm', muscles: 'lats · mid-back', equip: 'DB + chair', icon: '🫷', img: 'One-Arm_Dumbbell_Row', video: 'one+arm+dumbbell+row',
          cues: 'Elbow to hip; square torso', mistake: 'Twisting / jerking', prog: 'Supported → heavy → paused reps (subs for barbell row)' },
        { name: 'Standing DB Press', target: '3×8', muscles: 'delts · triceps', equip: 'DBs/KB', icon: '🫸', img: 'Dumbbell_Shoulder_Press', video: 'standing+dumbbell+press',
          cues: 'Squeeze glutes; biceps to ears', mistake: 'Leaning back', prog: 'Seated → standing → single-arm KB (subs for OHP)' },
        { name: 'Pallof Press', target: '2×12/side', muscles: 'obliques · deep core', equip: 'band', icon: '🧱', img: null, video: 'pallof+press+form',
          cues: 'Press straight out; resist the twist', mistake: 'Rotating toward the anchor', prog: 'Tall-kneeling → standing → walkout' },
        { name: 'Dead Bug / Hollow Hold', target: '3×10', muscles: 'deep core', equip: 'none', icon: '🪲', img: 'Dead_Bug', video: 'dead+bug+exercise',
          cues: 'Low back glued down; slow exhale', mistake: 'Ribs flaring', prog: 'Dead bug → hollow hold → hollow rocks' },
        { name: 'Single-Leg Glute Bridge', target: '3×10/leg', muscles: 'glutes', equip: 'none', icon: '🍑', img: 'Butt_Lift_Bridge', video: 'single+leg+glute+bridge',
          cues: 'Drive the heel; squeeze at top', mistake: 'Arching the low back', prog: 'Two-leg → single → shoulders-elevated +DB' },
      ]},
    ],
  },

  // ============================================================
  swim: {
    label: 'Swim',
    icon: '🏊',
    blurb: 'Strokes + drills for fitness swimming. Workout skeleton: warm-up → drills → main set → kick/pull → cool-down. “4×100 @ 2:00” = leave every 2 min.',
    groups: [
      { title: 'Strokes', items: [
        { name: 'Freestyle', target: 'default fitness stroke', muscles: 'lats · pecs · delts · core · legs', equip: 'pool', icon: '🏊', img: null, video: 'freestyle+swimming+technique',
          cues: 'Long horizontal line, eyes down · high-elbow catch · rotate from the hips', mistake: 'Lifting the head to breathe — hips sink', prog: 'Catch-up drill → fingertip drag → bilateral breathing' },
        { name: 'Backstroke', target: 'recovery stroke', muscles: 'lats · rear delts · core · glutes', equip: 'pool', icon: '🏊', img: null, video: 'backstroke+technique',
          cues: 'Flat head, eyes up, hips at surface · pinky-first entry at 11 & 1', mistake: '“Sitting” in the water when the head lifts', prog: 'Kick on back → single-arm → full stroke' },
        { name: 'Breaststroke', target: 'easy-day stroke', muscles: 'quads · glutes · adductors · pecs', equip: 'pool', icon: '🏊', img: null, video: 'breaststroke+technique',
          cues: 'Pull → breathe → kick → GLIDE · heels to hips, feet flexed, snap together', mistake: 'No glide — constant churning', prog: 'Kick on back → 2-kicks-1-pull → full timing. Note: whip kick can bug knees' },
        { name: 'Butterfly', target: 'short doses (25s)', muscles: 'lats · pecs · delts · core — fullest engagement', equip: 'pool', icon: '🏊', img: null, video: 'butterfly+stroke+technique',
          cues: 'Undulate from chest & hips · 2 dolphin kicks per cycle · low forward breath', mistake: 'Muscling with arms alone — gone in one length', prog: 'Body dolphin → 2-kicks-1-pull → full stroke 25s' },
      ]},
      { title: 'Drills', items: [
        { name: 'Catch-Up Drill', target: '4×50', muscles: 'freestyle timing', equip: 'pool', icon: '🤙', img: null, video: 'catch+up+drill+swimming',
          cues: 'One arm waits extended until the other completes a full stroke', mistake: 'Rushing the waiting arm', prog: 'Fix: rushing the pull' },
        { name: 'Fingertip Drag', target: '4×50', muscles: 'high-elbow recovery', equip: 'pool', icon: '🤙', img: null, video: 'fingertip+drag+drill',
          cues: 'Drag fingertips along the surface through recovery', mistake: 'Straight-arm swinging', prog: 'Fix: rushed, low recovery' },
        { name: 'Fist Drill', target: '2×50', muscles: 'forearm catch / feel', equip: 'pool', icon: '✊', img: null, video: 'fist+drill+swimming',
          cues: 'Swim with closed fists — forearm does the pulling', mistake: 'Dropping the elbow', prog: 'Open hands after — instant feedback' },
        { name: 'Single-Arm Free', target: '4×25/arm', muscles: 'stroke mechanics · rotation', equip: 'pool', icon: '🤙', img: null, video: 'single+arm+freestyle+drill',
          cues: 'One arm strokes, other extended in front', mistake: 'Flat hips, no rotation', prog: 'Extended → arm-at-side (advanced)' },
        { name: '6-Kick Switch', target: '4×50', muscles: 'side balance · rotation', equip: 'pool', icon: '🦶', img: null, video: '6+kick+switch+drill',
          cues: '6 kicks on the side, one stroke to rotate, repeat', mistake: 'Face forward instead of down', prog: 'Fix: balance & rotation' },
        { name: 'Sculling', target: '4×25', muscles: 'feel for the water', equip: 'pool (+buoy)', icon: '🖐️', img: null, video: 'sculling+drill+swimming',
          cues: 'Small figure-8 hand sweeps, face down, slow travel', mistake: 'Big paddling strokes', prog: 'Front scull → mid scull' },
        { name: 'Kickboard Kick Set', target: '4×50', muscles: 'legs · kick mechanics', equip: 'kickboard', icon: '🛹', img: null, video: 'kickboard+drills',
          cues: 'Steady flutter from the hips, hips near surface', mistake: 'Knee-driven bicycle kick', prog: 'Board → streamline kick on back' },
        { name: 'Pull Buoy Set', target: '4×75', muscles: 'upper-body pull', equip: 'pull buoy', icon: '🛟', img: null, video: 'pull+buoy+technique',
          cues: 'Buoy between thighs, no kick — pure catch & rotation', mistake: 'Snaking from no core tension', prog: 'Add paddles later (sparingly)' },
        { name: 'Streamline Glide + Kick', target: 'every wall', muscles: 'posture off walls', equip: 'pool', icon: '🚀', img: null, video: 'streamline+push+off',
          cues: 'Biceps behind ears, tight line, kick before surfacing', mistake: 'Surfacing immediately', prog: 'Add dolphin kicks underwater' },
        { name: 'Vertical Kicking', target: '4×20 s', muscles: 'kick power · core', equip: 'deep water', icon: '🕴️', img: null, video: 'vertical+kicking+drill',
          cues: 'Tread with flutter/dolphin only, arms crossed', mistake: 'Hands sneaking in', prog: '15 s → 30 s → weight overhead' },
      ]},
      { title: 'Example sessions', items: [
        { name: 'Easy Recovery Swim', target: '~30 min · 1200 m', muscles: 'active recovery (RPE 3–4)', equip: 'pool', icon: '🧘', img: null, video: 'easy+recovery+swim',
          cues: '200 easy · 4×50 drill · 6×100 easy free @ :20 rest · 4×25 back/breast · 100 easy', mistake: 'Letting it creep into a workout — keep it conversational', prog: 'Day after heavy legs or long run' },
        { name: 'Conditioning Swim', target: '~40 min · 1800 m', muscles: 'aerobic engine', equip: 'pool', icon: '🔥', img: null, video: 'swim+conditioning+workout',
          cues: '300 mix · 4×50 build @ 1:10 · 3×[2×100 @ 2:05 + 50 strong] · 4×75 pull · 150 easy', mistake: 'Sprinting the first round', prog: 'Descend 1–4 · shrink send-offs over weeks' },
      ]},
    ],
  },

  // ============================================================
  boxing: {
    label: 'Boxing',
    icon: '🥊',
    blurb: 'Numbers: odd = lead hand, even = rear. Classic combos: 1-2 · 1-1-2 · 1-2-3 · 2-3-2 · 1-2-3-2 · 1-2-5-2. Rounds: 3 min work / 1 min rest.',
    groups: [
      { title: 'Punches (1–6)', items: [
        { name: '1 · Jab', target: 'lead straight', muscles: 'shoulders · triceps · timing', equip: 'none', icon: '🥊', img: null, video: 'boxing+jab+technique',
          cues: 'Snap out from guard, fist rotates palm-down, straight back to the face', mistake: 'Lazy return — hand drops', prog: 'Mirror → bag → double jab' },
        { name: '2 · Cross', target: 'rear straight', muscles: 'hips · core rotation · triceps', equip: 'none', icon: '🥊', img: null, video: 'boxing+cross+technique',
          cues: 'Pivot the rear foot, rotate hips + shoulders, chin behind the shoulder', mistake: 'Arm-punching without hip rotation', prog: '1-2 rhythm on the bag' },
        { name: '3 · Lead Hook', target: 'lead bent-arm', muscles: 'obliques · lats · shoulders', equip: 'none', icon: '🥊', img: null, video: 'boxing+lead+hook+technique',
          cues: 'Elbow locked ~90°, pivot the lead foot (“squash the bug”), whole body turns', mistake: 'Winding up — telegraphs', prog: '1-2-3 flow' },
        { name: '4 · Rear Hook', target: 'rear bent-arm', muscles: 'rear-side rotation · glutes', equip: 'none', icon: '🥊', img: null, video: 'boxing+rear+hook',
          cues: 'Pivot hard on the rear foot; lead hand glued to the cheek', mistake: 'Squaring up, losing stance', prog: '2-3-4 on the pads' },
        { name: '5 · Lead Uppercut', target: 'lead upward', muscles: 'legs · biceps · core', equip: 'none', icon: '🥊', img: null, video: 'boxing+lead+uppercut',
          cues: 'Dip with the knees, drive UP through legs & hips, elbow stays bent', mistake: 'Dropping the hand to the waist first', prog: '1-2-5-2' },
        { name: '6 · Rear Uppercut', target: 'rear upward', muscles: 'posterior chain · hip extension', equip: 'none', icon: '🥊', img: null, video: 'boxing+rear+uppercut',
          cues: 'Load the rear side, rotate hips as the fist arcs up tight', mistake: 'Looping it wide like a hook', prog: '6-3-2 close-range combo' },
      ]},
      { title: 'Footwork & defense', items: [
        { name: 'Stance Check', target: 'daily 2 min', muscles: 'base position', equip: 'mirror', icon: '🧍', img: null, video: 'boxing+stance+basics',
          cues: 'Feet diagonal shoulder-width+, rear heel up, hands at cheeks, chin tucked', mistake: 'Feet on one line — no balance', prog: 'Hold stance through combos' },
        { name: 'Step-Drag', target: '3 min round', muscles: 'footwork base', equip: 'none', icon: '👣', img: null, video: 'boxing+step+drag+footwork',
          cues: 'Near foot steps first, trailing foot drags back to width; never cross', mistake: 'Hopping / feet clicking together', prog: 'Forward-back → lateral → with jab' },
        { name: 'Pivot', target: '3 min round', muscles: 'angles', equip: 'none', icon: '🌀', img: null, video: 'boxing+pivot+technique',
          cues: 'Rotate on the ball of the lead foot, rear foot swings around', mistake: 'Standing tall mid-pivot', prog: '10–15° → 90° → pivot after combos' },
        { name: 'Slip', target: '3×20', muscles: 'head movement', equip: 'none', icon: '↔️', img: null, video: 'boxing+slip+technique',
          cues: 'Small head shift off the line, bend knees + waist, eyes on target', mistake: 'Leaning instead of slipping — off balance', prog: 'Slip line/rope drill' },
        { name: 'Roll / Weave', target: '3×20', muscles: 'legs · core', equip: 'none', icon: '🌊', img: null, video: 'boxing+roll+under+technique',
          cues: 'Trace a “U” under the hook with the legs, come up ready to punch', mistake: 'Bending the back, not the knees', prog: 'Roll under a rope → 3-roll-3' },
        { name: 'Block / Parry', target: '3×20', muscles: 'guard skills', equip: 'none', icon: '🛡️', img: null, video: 'boxing+block+parry',
          cues: 'Glove glued to cheekbone to block; light open-hand tap to parry straights', mistake: 'Reaching for the parry', prog: 'Block → parry-counter (parry-2)' },
      ]},
      { title: 'Training methods', items: [
        { name: 'Shadowboxing', target: '3×3 min', muscles: 'technique · flow', equip: 'none', icon: '👤', img: null, video: 'shadow+boxing+workout',
          cues: 'Imagine a real opponent; move after every combo', mistake: 'Standing still throwing arms', prog: 'Theme rounds: footwork-only → defense-only → free' },
        { name: 'Heavy Bag', target: '4–6×3 min', muscles: 'power · conditioning', equip: 'bag + gloves', icon: '🥊', img: null, video: 'heavy+bag+workout+beginner',
          cues: 'Snap punches, don’t push; keep moving around the bag', mistake: 'Pushing the bag — no snap', prog: 'Jabs/1-2 → add hooks → add uppercuts → 15 s max bursts' },
        { name: 'Pad Work', target: '3×3 min', muscles: 'accuracy · reactions', equip: 'partner + mitts', icon: '🎯', img: null, video: 'boxing+pad+work+combos',
          cues: 'Listen for the numbers, reset to guard after every combo', mistake: 'Admiring your work — hands drop', prog: 'Set combos → coach-called → add defense between' },
        { name: 'Skipping Rope', target: '3×3 min', muscles: 'calves · rhythm · footwork', equip: 'rope', icon: '➰', img: null, video: 'boxing+jump+rope+basics',
          cues: 'Balls of the feet, wrists spin the rope', mistake: 'Arms swinging wide', prog: 'Two-foot bounce → boxer skip → double-unders' },
        { name: 'Double-End Bag', target: '2–3×3 min', muscles: 'timing · accuracy', equip: 'double-end bag', icon: '🎯', img: null, video: 'double+end+bag+basics',
          cues: 'Start with single jabs, find the rhythm before combos', mistake: 'Swinging hard at a fast target', prog: 'Jab → 1-2 → slip + counter' },
        { name: 'Roadwork', target: '20–45 min', muscles: 'aerobic base', equip: 'shoes', icon: '🏃', img: 'Running_Treadmill', video: 'boxing+roadwork+training',
          cues: 'Mix steady runs with fartlek pace changes that mimic rounds', mistake: 'Only long slow miles', prog: 'LSD → fartlek → hill sprints' },
        { name: 'Conditioning Circuit', target: '3 min rounds · 40 s on/20 s off', muscles: 'full body · punching muscles', equip: 'bodyweight/med ball', icon: '🔥', img: null, video: 'boxing+conditioning+circuit',
          cues: 'Burpees · squats · push-ups · planks · med-ball slams at round pace', mistake: 'Pacing it like a stroll — keep round intensity', prog: 'Add rounds; shrink rests to :15' },
      ]},
    ],
  },
};

// ============================================================
// Anatomy reference (info-only tab)
// ============================================================
const LIB_ANATOMY = {
  muscles: [
    { name: 'Pecs (chest)', where: 'Front of chest', does: 'Push arm forward/across', ex: 'Bench press · push-up · fly' },
    { name: 'Lats', where: 'Broad mid/lower back', does: 'Pull arm down/back', ex: 'Pull-up · pulldown · row' },
    { name: 'Traps', where: 'Neck → mid-back', does: 'Shrug, pull blades back/down', ex: 'Shrug · face pull · carries' },
    { name: 'Rhomboids', where: 'Between shoulder blades', does: 'Squeeze blades together', ex: 'Row · reverse fly' },
    { name: 'Delts (3 heads)', where: 'Shoulder cap', does: 'Raise arm front/side/rear', ex: 'OHP · lateral raise · reverse fly' },
    { name: 'Biceps', where: 'Front upper arm', does: 'Bend elbow, turn palm up', ex: 'Curl · chin-up · row' },
    { name: 'Triceps', where: 'Back upper arm', does: 'Straighten elbow', ex: 'Dip · pushdown · close-grip press' },
    { name: 'Forearms / grip', where: 'Elbow → wrist', does: 'Grip, wrist motion', ex: 'Dead hang · farmers carry' },
    { name: 'Abs (rectus)', where: 'Front of trunk', does: 'Curl spine, brace', ex: 'Crunch · hanging leg raise' },
    { name: 'Obliques', where: 'Sides of waist', does: 'Rotate / side-bend / resist both', ex: 'Pallof press · side plank · wood-chop' },
    { name: 'Deep core (TVA)', where: 'Deep belly wrap', does: 'Pressure + spine stability', ex: 'Plank · dead bug' },
    { name: 'Erector spinae', where: 'Along the spine', does: 'Keep back upright / extend', ex: 'Deadlift · back extension' },
    { name: 'Glute max', where: 'Butt', does: 'Drive hips forward', ex: 'Squat · hip thrust · sprint' },
    { name: 'Glute med', where: 'Side of hip', does: 'Stabilize pelvis on one leg', ex: 'Band walk · single-leg work' },
    { name: 'Quads', where: 'Front thigh', does: 'Straighten knee', ex: 'Squat · lunge · leg extension' },
    { name: 'Hamstrings', where: 'Back thigh', does: 'Bend knee + drive hips', ex: 'RDL · leg curl · Nordic' },
    { name: 'Adductors', where: 'Inner thigh', does: 'Pull leg inward, stabilize', ex: 'Sumo squat · Copenhagen plank' },
    { name: 'Calves (gastroc/soleus)', where: 'Back lower leg', does: 'Point the foot, push off', ex: 'Standing & seated calf raise' },
    { name: 'Hip flexors', where: 'Front of hip', does: 'Lift the knee', ex: 'Leg raise · L-sit · sprint knees' },
  ],
  pairs: [
    ['Chest ↔ Back', 'Press without pulling → rounded shoulders. Row as much as you press.'],
    ['Quads ↔ Hamstrings', 'Weak hamstrings raise knee/ACL risk. Hinge as much as you squat.'],
    ['Abs ↔ Lower back', 'Front-and-back core keeps the spine safe under load.'],
    ['Front ↔ Rear delts', 'Rear-delt work fixes pressing/desk posture.'],
    ['Hip flexors ↔ Glutes', 'Sitting tightens flexors + sleeps glutes — train the bridge/thrust.'],
    ['Biceps ↔ Triceps', 'Balanced elbow strength, healthy tracking.'],
  ],
  adapt: [
    ['Strength', '1–5 reps · heavy (≥80% max) · rest 2–5 min. Teaches the nervous system to produce force.'],
    ['Muscle (hypertrophy)', '~6–12+ reps near failure. Volume is king: ~10–20 hard sets per muscle per week, split over 2+ sessions.'],
    ['Endurance', '15+ reps light. Modest, mostly lower-body carryover.'],
    ['Progressive overload', 'Add weight, reps or sets over time — no increase, no adaptation.'],
    ['Recovery', 'Muscle rebuilds for ~24–48 h after training. Hit each muscle hard ~every 48–72 h → ~2×/week beats 1×.'],
    ['Mind–muscle', 'On isolation moves, focusing on the muscle can boost growth. On heavy compounds, focus on moving the bar.'],
  ],
};
